### ISSUE TITLE
General UX issues

### ISSUE THREAD

**Issue by mix3d** [U-C-S/Hurl#89]
There are some standard patterns that someone just exploring the application will run into. 

Things like the ability to "go back" when opening a setting, etc. 

Main items I've noticed:
* Tooltips missing on hover (What does x button do)
* Clicking the "choose a browser for X minutes" button (clock icon) cannot be cancelled, the X button closes the window without returning to the main HURL window.
* Clicking the settings button (gear icon) opens notepad (no way to choose an OS-default file handler for that type?), and closes the HURL window. I think I understand WHY this is important, because if you change the settings while HURL is open that could be bad, but since this appears to be a "load settings into memory from json file on launch", and there's no pretty editor (yet), this shouldn't be an issue so long as you manually close and reopen again.
  * Maybe an interstitial "we're going to close HURL and open the config, do you want to continue?"
* Opening HURL directly, then clicking on of the browser options prompts to download the Hurl DLL (instead of a new, empty browser window).

My main point with these is that it's jarring to unfamiliar users to not be able to go back to the context you started from, when clicking things.

**Comment by U-C-S** [comment]
Thanks for pointing out the issues, will use this as checklist to come up with solutions and fix them for next patch release.

- [x] Tooltips missing on hover (What does x button do)
- [ ] Clicking the "choose a browser for X minutes" button (clock icon) cannot be cancelled, the X button closes the window without returning to the main HURL window.
- [ ] Clicking the settings button (gear icon) opens notepad (no way to choose an OS-default file handler for that type?), and closes the HURL window. I think I understand WHY this is important, because if you change the settings while HURL is open that could be bad, but since this appears to be a "load settings into memory from json file on launch", and there's no pretty editor (yet), this shouldn't be an issue so long as you manually close and reopen again.
  * Maybe an interstitial "we're going to close HURL and open the config, do you want to continue?"
- [ ] Opening HURL directly, then clicking on of the browser options prompts to download the Hurl DLL (instead of a new, empty browser window).

**Comment by Jay-o-Way** [comment]
@U-C-S About the opening of the settings file, with default app: I would search something more direct than using "explorer.exe". For example: https://www.c-sharpcorner.com/article/shell-commands-within-C-Sharp/#:~:text=Open%20a%20specific%20document%20in%20Microsoft%20Word.
